---
title: "analysis of my first article"
description: Study of certain dolphin capacities.
author:
  - name: Marlier Nicolas 
    url: {}
date: 10-26-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
# SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT

source: [https://www.sciencenews.org/article/dolphins-learn-shells-foraging-tools]

date: June 25, 2020

world count: 633

# VOCABULARY


| Word from the text | Synonym/definitionin English                                                                                                                                                                                         | French translation        |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------- |
| Peers              | one who is the equal of another  in abilities or social status                                                                                                                                                       | pairs                     |
| Shells             | a hard outer covering of an animal,  such as of a clam, snail, or turtle                                                                                                                                             | coquilles                 |
| Tools              |  anything used to accomplish a task                                                                                                                                                                                  | outils                    |
| Foraging           | to wander or go in search of provisions                                                                                                                                                                              | r recherche de nourriture |
| Porpoise           | a marine mammal having a blunt,  rounded snout and resembling a dolphin                                                                                                                                              | marsouin                  |
| Humpback whales    | a large whalebone whale of the genus  Megaptera having long narrow flippers, and noted for its habit of arching  deeply as it dives: once abundant in coastal waters, it is now rare but its numbers are increasing. | Baleine à bosse           |
| Beak               | any horny or stiff mouthpart of an animal that sticks out or is curved like a bird's                                                                                                                                 | bec                       |
| Prey               | an animal hunted for food                                                                                                                                                                                            | proie                     |
| mind-blowing       | overwhelming ; astounding                                                                                                                                                                                            | époustouflant             |
| relatedness        | associated or connected by family,  marriage, or common origin                                                                                                                                                       | ° de parenté              |
| overlap            | to have something in common or come together partly with (another)                                                                                                                                                   | chevauchement             |
| to occur           |  to happen; take place                                                                                                                                                                                               | avoir lieu                |
# ANALYSIS ABOUT THE STUDY 

**Researchers?**  
author: Jack J. Lee                                                                 
Wild (graduate student at the University of Leeds in England)                       
Janet Mann (a biologist at Georgetown University in Washington, D.C)
                                 

**Published in? when?**    
sciencesnews  June 25, 2020



**General topic**     
dolphin's ability to learn and use shells as tools



**Procedure/ what was examined**     
studies of groups of dolphins certain                                                environments


**Conclusions/ discovery**
-verry smart annimal                                                                
-learn from is mother                                                               
-learn from other dolphin                                                           
-use shell to hunt





